### ISSUE TITLE
edit button doesn't work

### ISSUE THREAD

**Issue by jtr13** [jeroenjanssens/data-science-at-the-command-line#105]
an `edit:` line is needed in `_bookdown.yml`:

https://bookdown.org/yihui/bookdown/configuration.html

(I wasn't trying to edit, just see the GitHub repo.)

**Comment by jeroenjanssens** [comment]
Thanks for bringing this up, @jtr13 ! 

The `edit:` line in *_bookdown.yml* was there, but apparently I also needed to update the path in *_output.yml*. 

Anyway, editing works again :)
