### ISSUE TITLE
A typo: replace 'tools' with 'tool'

### ISSUE THREAD

**Issue by borispov** [jeroenjanssens/data-science-at-the-command-line#112]
https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/4cfb32499f09ea50e7ecd73c00d475cf8a48da1e/book/2e/02.Rmd#L517

"Sometimes a tools or sequence of tool produces too much output to include in the book. Instead of manually altering such output, I prefer to be transparent by I piping it through a helper tool."

Looks to me that you meant:
a) Sometimes a tool or sequence of tools produce too much ...
b) I prefer to be transparent by piping it through ...

**Comment by ciotog** [comment]
Agreed, except:
"Sometimes a tool or sequence of tools produces too much ..."

Since "tool" and "sequence of tools" are both singular.

**Comment by jeroenjanssens** [comment]
Thanks @borispov and @ciotog!
