### ISSUE TITLE
first edition, ch5, heading 5.4, scrape script throws error AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by armenic** [jeroenjanssens/data-science-at-the-command-line#113]
Dear Author,

Thank you so much for an awesome book! I enjoy every page of it.
While doing the examples in ch5, header ch5.4 I encountered the following error and here are the reproducible steps:

docker image:

`datasciencetoolbox/dsatcl2e   latest    ae2a972cf9a6   3 weeks ago    2.67GB`

commands submitted:
```bash
curl -sL 'http://en.wikipedia.org/wiki/List_of_countries_and_territories_by_border/area_ratio' > wiki.html
< wiki.html scrape -b -e 'table.wikitable > tr:not(:first-child)' > table.html
```

error:
```
Traceback (most recent call last):
  File "/usr/bin/dsutils/scrape", line 78, in <module>
    exit(main())
  File "/usr/bin/dsutils/scrape", line 37, in main
    args.expression = [e.decode('utf-8') for e in args.expression]
  File "/usr/bin/dsutils/scrape", line 37, in <listcomp>
    args.expression = [e.decode('utf-8') for e in args.expression]
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by aborruso** [comment]
@armenic in the book I do not see this CSS selector query `table.wikitable > tr:not(:first-child)`.

Anyway it seems to me wrong. Try to use `table.wikitable tr:not(:first-child)`. You can test it also via browser

![image](https://user-images.githubusercontent.com/30607/123554399-1b601700-d780-11eb-85ee-c0bf643ac67f.png)

**Comment by armenic** [comment]
thanks @aborruso, sorry my mistake, it was in the first edition https://www.datascienceatthecommandline.com/1e/chapter-5-scrubbing-data.html#working-with-xmlhtml-and-json 
I appreciate that there is an issue with selector and please pay attention to the error. Apparently in the scrape Python script the author used decode method on the string which does not exist in Python 3.9.5

![image](https://user-images.githubusercontent.com/71098506/123560019-c3b8b000-d76d-11eb-95bd-920120a900cc.png)

**Comment by jeroenjanssens** [comment]
Thank you @armenic and @aborruso for your feedback. In the second edition `scrape` has been replaced by `pup`, so this is no longer an issue.
