### ISSUE TITLE
Generate ePUB from repo

### ISSUE THREAD

**Issue by halloleo** [jeroenjanssens/data-science-at-the-command-line#116]
Firstly I wanted to say that I really like this book and I think it is great to see the 2nd edition coming.

Reading the book online is good, but an ePUB would help even more. I had a look at the Makefile, but couldn't see that it enable generating an ePUB.

So, are we allowed to make an ePUB from this repo plus is there a command for this already?

**Comment by jeroenjanssens** [comment]
Thank you for your kind words. 

I only asked (and got) permission to publish an HTML version of the book. I won't be able to help you with generating an ePUB version, but if you can figure it out yourself using the generated Markdown or HTML and not distribute it, then I guess that should be OK.
