### ISSUE TITLE
Downloaded file `top2000.xlsx` used in ch03 in 2e is removed from the website

### ISSUE THREAD

**Issue by tddschn** [jeroenjanssens/data-science-at-the-command-line#118]
`curl "https://www.nporadio2.nl/data/download/TOP-2000-2020.xlsx" > top2000.xlsx` no longer works, 
since the file `TOP-2000-2020.xlsx` is removed from the site,
 and the downloaded file `top2000.xlsx` is a 404 HTML file.

Maybe consider including the file in the repository?

**Comment by tddschn** [comment]
This file is indeed included in the repo, it was just overwriten by curl. :(

**Comment by jeroenjanssens** [comment]
Thanks Ted. I can't believe I have missed this issue for so long...

Anyway, I have changed to the online text so that it indeed uses the file in the repo. Thanks again.
