### ISSUE TITLE
Chapter 9 is missing files, so command outputs mostly show errors

### ISSUE THREAD

**Issue by JakubWagner1019** [jeroenjanssens/data-science-at-the-command-line#129]
https://datascienceatthecommandline.com/2e/chapter-9-modeling-data.html

It is most likely due to typo when copying files in 9.2 chapter
$ p /data/.cache/wine-*.csv . 
zsh: command not found: p

**Comment by jeroenjanssens** [comment]
Ouch, that's pretty bad. Thanks for letting me know. I just fixed it.

**Comment by JakubWagner1019** [comment]
Awesome! Thank YOU for creating such a great book and fixing the issue this fast.
