### ISSUE TITLE
Docker image Installation fails

### ISSUE THREAD

**Issue by shmuhammadd** [jeroenjanssens/data-science-at-the-command-line#132]
Hi,

I tried to install docker image at chapter 2, but it fails. Below is the error:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Best,
Shamsuddeen

**Comment by jeroenjanssens** [comment]
Hi Shamsuddeen,

Good to see that you want to use the Docker image. This error is related to Docker itself and it means that you're probably not yet running Docker. Because this has nothing to do with the image, I'm closing this issue. 

Good luck!

Jeroen
