### ISSUE TITLE
Command render wrong in website book

### ISSUE THREAD

**Issue by persep** [jeroenjanssens/data-science-at-the-command-line#137]
This [line ](https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/44cddf60fdbb1a598f1e253b560346c90bce88b7/book/2e/02.Rmd#LL94C58-L94C58) renders as
![image](https://github.com/jeroenjanssens/data-science-at-the-command-line/assets/1191676/cf29a1e8-687d-4d6e-a358-3c3de9343ff8)
 in the official book [website](https://jeroenjanssens.com/dsatcl/chapter-2-getting-started.html) with the latest firefox 113.0.1 and Edge Version 113.0.1774.50 (Official build) (64-bit) in windows 10
When the correct command is:
`$ docker run --rm -it -v "$(pwd)":/data datasciencetoolbox/dsatcl2e`

**Comment by jeroenjanssens** [comment]
Thanks! Fixed.
