### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by persep** [jeroenjanssens/data-science-at-the-command-line#138]
At
`https://jeroenjanssens.com/dsatcl/chapter-1-introduction.html`

There is a link to
`https://datascienceatthecommandline.com/resources/50-reasons.pdf`

From this file
https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/44cddf60fdbb1a598f1e253b560346c90bce88b7/book/2e/01.Rmd#L299

That returns an error not found

**Comment by jeroenjanssens** [comment]
Thanks! Fixed.
