### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by persep** [jeroenjanssens/data-science-at-the-command-line#139]
Where it says:
https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/44cddf60fdbb1a598f1e253b560346c90bce88b7/book/2e/02.Rmd#L324

`they are designed to do only thing, and do it really well`

It should say:
`they are designed to do only one thing, and do it really well`

**Comment by jeroenjanssens** [comment]
Thanks! Fixed.
