### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by persep** [jeroenjanssens/data-science-at-the-command-line#140]
At 
https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/44cddf60fdbb1a598f1e253b560346c90bce88b7/book/2e/02.Rmd#L377

where it says
`The file will be saved it in the current directory`

It should say
`The file will be saved in the current directory`

**Comment by jeroenjanssens** [comment]
Thanks! Fixed.
