### ISSUE TITLE
ch03 curl commands for downloading top2000.xlsx no longer work

### ISSUE THREAD

**Issue by knbknb** [jeroenjanssens/data-science-at-the-command-line#145]
The Dutch radiostation  has redesigned their web site, so the URL (see below) is dead.  
No  problem, the `top2000.xlsx` file is in `data.zip`.  
However aLso the rendered webpages of your book also contain semantically  invalid content:

Ch 3.5 

```Before, Bad
# top2000
curl "https://www.nporadio2.nl/data/download/TOP-2000-2020.xlsx" > top2000.xlsx
BadZipFile: File is not a zip file
```

should be 

```After, good
NR.,ARTIEST,TITEL,JAAR
1,Danny Vera,Roller Coaster,2019
2,Queen,Bohemian Rhapsody,1975
...
```

**Comment by jeroenjanssens** [comment]
Thanks for letting me know. I found the new URL and I have fixed the HTML accordingly.
