### ISSUE TITLE
New tool to format data into tables

### ISSUE THREAD

**Issue by danchoi** [jeroenjanssens/data-science-at-the-command-line#31]
I'm releasing a new tool that might be useful to the data science toolkit. (I don't know how else to inform you about it @jeroenjanssens other than a GitHub issue, since I don't use Twitter.)

https://github.com/danchoi/table

`table` formats lines of TSV, CSV, or DSV (delimiter-separated values) into a pretty plain text table, wrappings cells with long content to try to fit the table in the screen.

**Comment by jeroenjanssens** [comment]
Thanks for letting me know. Looks good!
