### ISSUE TITLE
cols not working

### ISSUE THREAD

**Issue by vaheandonians-scdm** [jeroenjanssens/data-science-at-the-command-line#32]
It seems like cols is not working.
No matter how I run it, I always get this response:

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
mkfifo: /other_columns: Permission denied
/Applications/command-line-tools/cols: line 24: ${ARG~~}: bad substitution
tee: /other_columns: Permission denied

**Comment by jeroenjanssens** [comment]
On what OS are you?

**Comment by vaheandonians-scdm** [comment]
Mac OS X latest version.
thx

On Friday, January 2, 2015, Jeroen Janssens <notifications@github.com>
wrote:

> On what OS are you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenjanssens/data-science-at-the-command-line/issues/32#issuecomment-68556521>
> .
>
> ***********************************************************
> This message may contain confidential and/or privileged
> information. If you are not the addressee or authorized to
> receive this for the addressee, you must not use, copy,
> disclose or take any action based on this message or any
> information herein. If you have received this message in
> error, please advise the sender immediately by reply e-mail
> and delete this message. Thank you for your cooperation.
> ***********************************************************



-- 
***********************************************************
This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy,
disclose or take any action based on this message or any
information herein. If you have received this message in
error, please advise the sender immediately by reply e-mail
and delete this message. Thank you for your cooperation.
***********************************************************

**Comment by jeroenjanssens** [comment]
I'm not able to test this on a Mac, so please let me know if it works for you. Thanks.

**Comment by vaheandonians-scdm** [comment]
Dear Joroen,
I pulled the code and tried it. Unfortunately same result:
[image: Inline image 2]
I have also attached the fashion.csv file.
Sorry for the inconvenience.
Best regards,
Vahe

***********************************************************
This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy,
disclose or take any action based on this message or any
information herein. If you have received this message in
error, please advise the sender immediately by reply e-mail
and delete this message. Thank you for your cooperation.
***********************************************************

**Comment by jeroenjanssens** [comment]
I'm not seeing any attachments, so can you please include the exact command and the error message your getting (as text)?

**Comment by vaheandonians-scdm** [comment]
Dear Jeroen,
I am reading the book "Data Science at the Command Line" and running
this command:
< fashion.csv cols -c date cut -dT -f1 | head | csvlook
All previous commands were fine.
The result is:

vaheandonians@gauss:~/data-science/ch01/data$ < fashion.csv cols -c
date cut -dT -f1 | head | csvlook

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...

       mktemp [-d] [-q] [-u] -t prefix

mkfifo: /other_columns: Permission denied

/Applications/command-line-tools/cols: line 24: ${ARG~~}: bad substitution

tee: /other_columns: Permission denied

|-------------+---|

|  date       |   |

|-------------+---|

|  2014-12-18 |   |

|  2014-12-04 |   |

|  2014-12-21 |   |

|  2014-11-23 |   |

|  2014-12-21 |   |

|  2014-12-11 |   |

|  2010-09-09 |   |

|  2014-11-21 |   |

|  2012-09-16 |   |

|-------------+---|

Best regards,
Vahe
***********************************************************
This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy,
disclose or take any action based on this message or any
information herein. If you have received this message in
error, please advise the sender immediately by reply e-mail
and delete this message. Thank you for your cooperation.
***********************************************************

**Comment by jeroenjanssens** [comment]
Thanks. These error messages indicate that you're not using the updated version of `cols`. Please check whether you're pulling the changes correctly.

**Comment by vaheandonians-scdm** [comment]
Ok, I am an idiot. I pulled it but had not copied it to the path, thus it
was using the old files.
Sorry!!
Best regards,
Vahe

***********************************************************
This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy,
disclose or take any action based on this message or any
information herein. If you have received this message in
error, please advise the sender immediately by reply e-mail
and delete this message. Thank you for your cooperation.
***********************************************************

**Comment by jeroenjanssens** [comment]
No worries! ;) Just to be sure: does it work now?

**Comment by vaheandonians-scdm** [comment]
yes it works perfectly. Thank you!

***********************************************************
This message may contain confidential and/or privileged
information. If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy,
disclose or take any action based on this message or any
information herein. If you have received this message in
error, please advise the sender immediately by reply e-mail
and delete this message. Thank you for your cooperation.
***********************************************************

**Comment by jeroenjanssens** [comment]
You're welcome. Thanks for opening the issue. Don't hesitate to open another one when you encounter any problems with the other tools.
