### ISSUE TITLE
Scrape trin Golang

### ISSUE THREAD

**Issue by Immortalin** [jeroenjanssens/data-science-at-the-command-line#36]
Hi, do you mind writing a version of the scrape utility in Golang for better cross platform support? Thanks in advance!

**Comment by jeroenjanssens** [comment]
You should check out pup, which is written in Golang:
https://github.com/EricChiang/pup

Jeroen

On Saturday, March 21, 2015, Immortalin <notifications@github.com> wrote:

> Hi, do you mind writing a version of the scrape utility in Golang for
> better cross platform support? Thanks in advance!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenjanssens/data-science-at-the-command-line/issues/36>
> .
>


-- 
Jeroen Janssens
jeroenjanssens.com
@jeroenhjanssens <http://twitter.com/jeroenhjanssens>

**Comment by jeroenjanssens** [comment]
I assume that `pup` is to your liking, so I'm closing this.

**Comment by Immortalin** [comment]
Thanks for the recommendation!
