### ISSUE TITLE
Document how to provision this image on AWS or other cloud server

### ISSUE THREAD

**Issue by vielmetti** [jeroenjanssens/data-science-at-the-command-line#37]
I'm sure it must be possible to install this set of tools directly onto a server running on AWS; I don't know yet if the supplied information supports this directly.

I have the `vagrant-aws` plugin for `vagrant` running.

Ah - some more searching - the directions (which are quite good) are at 

http://datasciencetoolbox.org/

and select the tab "In the cloud"; that should be enough info to get it running.

**Comment by jeroenjanssens** [comment]
I'm no longer maintaining the AWS version, so I'm closing this. In case you're interested, there's now a Dockerfile: https://hub.docker.com/r/datascienceworkshops/data-science-at-the-command-line/
