### ISSUE TITLE
Rio-scatter to tty should display plot on X11

### ISSUE THREAD

**Issue by ole-tange** [jeroenjanssens/data-science-at-the-command-line#40]
This will dump a PNG file to the tty:

< iris.csv Rio-scatter sepal_length sepal_width species 

You never want that. If the output is not redirected to a file, display it on the screen with R's native displayer.

To see if stdout is a terminal you can use:

if [ -t 1 ] ; then
...
fi

**Comment by jeroenjanssens** [comment]
Thanks Ole, that's a good idea. I would fix this in `Rio` itself. What do you mean with R's native displayer? Do you know how to invoke it from the command line? So far, I've been using `display` from ImageMagick because it accepts standard input.

**Comment by ole-tange** [comment]
I mean something like this:

    R -e 'X11();plot(sin, -pi, 2*pi);Sys.sleep(10)'

One of the nice things is that you can resize the window and have the plot redrawn.

**Comment by jeroenjanssens** [comment]
It's a good idea, but I don't have time to implement this myself. If anyone is still interested, please submit a PR.
