### ISSUE TITLE
Rio -r flag

### ISSUE THREAD

**Issue by crazyhottommy** [jeroenjanssens/data-science-at-the-command-line#42]
-r flag loads the dplyr library, but I got error:

cat iris.csv | Rio -e -r -v "df %>% group_by(species) %>% mean(sepal_length)"
Error: object 'r' not found
Execution halted
cat: /var/folders/h5/3xs5c90n0njgp7n9_qdwwj2m0000gn/T//Rio-OLVgmOU2.err: No such file or directory

**Comment by jeroenjanssens** [comment]
`-r` is being interpreted as the expression. The solution is to move `-e` right before the expression:

    cat iris.csv | Rio -vre "df %>% group_by(species) %>% mean(sepal_length)"
