### ISSUE TITLE
Adding the data science toolbox to homebrew repository

### ISSUE THREAD

**Issue by antontarasenko** [jeroenjanssens/data-science-at-the-command-line#43]
The toolbox is great, as well as the book. But insofar as the book and the tools are so easy to use, perhaps, it's worth adding the tools to the `homebrew` repository as a single package? Or maybe to add readme describing how to install the tools without installing the environment, which is described in the book?

**Comment by jeroenjanssens** [comment]
Thanks for the kind words. I don't have the knowledge nor the time to take care of a homebrew formula, so I'm closing this issue. If anyone else interested in taking on this task, please open up a new issue.
