### ISSUE TITLE
sql2csv --db "mysql: ..." says I don't have the necessary backend installed

### ISSUE THREAD

**Issue by dylntrnr** [jeroenjanssens/data-science-at-the-command-line#46]
vagrant@data-science-toolbox:~$ sql2csv --db "mysql://user:password@10.0.2.2:3306/database" --query "select count(*) from session" 
You don't appear to have the necessary database backend installed for connection string you're trying to use.. Available backends include:

Postgresql:	pip install psycopg2
MySQL:		pip install MySQL-python

For details on connection strings and other backends, please see the SQLAlchemy documentation on dialects at: 

http://www.sqlalchemy.org/docs/dialects/

To fix I did:

sudo apt-get update
sudo apt-get install libmysqlclient-dev
sudo pip install MySQL-python

**Comment by jeroenjanssens** [comment]
This is actually more a csvkit-specific question, but I'm happy you figured it out!

**Comment by a-djebali** [comment]
Thanks a lot @dylntrnr , you saved my time ;)

**Comment by dylntrnr** [comment]
@jeroenjanssens I was just playing around with the new docker version and noticed that this issue also exists after pulling that latest docker image. Are you able to run any sql2csv commands when connecting to a mysql db with the docker image?

**Comment by calebeaires** [comment]
I hade this problem to. Still persists
