### ISSUE TITLE
scrape does not accept right XPath query?

### ISSUE THREAD

**Issue by aborruso** [jeroenjanssens/data-science-at-the-command-line#47]
Hi,
I need to do this query

```
curl -L -s -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0" "http://www.unionesulserio.it"  | /usr/local/bin/nadir/scrape -be '(//a[(contains(.,"pretorio")) or (contains(.,"Pretorio"))])[1]'
```

I have tested `(//a[(contains(.,"pretorio")) or (contains(.,"Pretorio"))])[1]` XPath query with other tools and it seems to work, but scrape gives me "Invalid CSS selector".

Is my XPath really wrong?

Thank you

**Comment by jeroenjanssens** [comment]
I believe this is because `scrape` only interprets the expression as an XPath when it starts with "//". Apparently not a good heuristic. One way to solve it is to add a flag. I don't have time to implement this myself, but if anyone else is interested in fixing this, please submit a PR.
