### ISSUE TITLE
Sequence of dates

### ISSUE THREAD

**Issue by hroptatyr** [jeroenjanssens/data-science-at-the-command-line#48]
Allow me to introduce my [dateutils](http://www.fresse.org/dateutils/), along with its `dateseq` command to produce sequences of dates (or date/times) not only faster but more portable and flexible.

Your semantics (you specify dates as day difference relative to today) would have to go through `dateadd` first though, as all tools in the toolkit take absolute dates.  Your example from the book would hence become:

```
$ dateseq `dateadd today -2` today
2016-03-19
2016-03-20
2016-03-21
```

So I suppose one could write a wrapper so your `dseq` tool wouldn't break its API.

**Comment by jeroenjanssens** [comment]
Thanks for letting me know about `dateutils`. I'll keep it in mind.
