### ISSUE TITLE
Wrong return code

### ISSUE THREAD

**Issue by tonyfischetti** [jeroenjanssens/data-science-at-the-command-line#51]
There are some places that return a non-successful error code (anything but 0) when there's no error. For example, https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/master/tools/header#L65

This is a big problem because some interprocess communication tools fail because they depend on a successful exit status. Should I submit a pull-request?

**Comment by jeroenjanssens** [comment]
Ouch! Thanks for catching that @tonyfischetti. A pull-request would be great.
