### ISSUE TITLE
Scrape in python 3 env

### ISSUE THREAD

**Issue by KeremTurgutlu** [jeroenjanssens/data-science-at-the-command-line#55]
Seems not to be working with python 3 versions. 

args.expression = [e.decode('utf-8') for e in args.expression]
AttributeError: 'str' object has no attribute 'decode'

**Comment by Nuttenscl** [comment]
a few things to make it work:
- decode & encode can be removed in python 3.
- basestringremoved in python 3
so practically:
- e.decode('utf-8') to become e   ([here](https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/8844ba9241f2efd323ba4434b002b26f276f1dad/tools/scrape#L37)
- text.encode('utf-8').strip() =>to become  str(text.strip())   ([here](https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/8844ba9241f2efd323ba4434b002b26f276f1dad/tools/scrape#L69)
- isinstance(e, basestring) => isinstance(e, str) ([here](https://github.com/jeroenjanssens/data-science-at-the-command-line/blob/8844ba9241f2efd323ba4434b002b26f276f1dad/tools/scrape#L62)

then it should work

**Comment by jeroenjanssens** [comment]
Thank you for these suggestions. If scrape will return in the second edition then I will make sure to make it work with Python 3. There is a chance that scrape will be replaced by a better alternative such as pup. 

I have recently moved this tool to another repository: [jeroenjanssens/dsutils](https://github.com/jeroenjanssens/dsutils). Feel free to continue the discussion there. Thanks again.
