### ISSUE TITLE
Vagrant up issues

### ISSUE THREAD

**Issue by roumail** [jeroenjanssens/data-science-at-the-command-line#56]
Hi,

I am having trouble starting the VM using vagrant up. I have tried on both windows and ubuntu. 
I get to the password/private key authentication part and can progress no further. Working with the VirtualBox GUI doesn't help either. 

Is there any other information I can provide to help diagnose the problem? My Vagrant config file is quite basic (mostly defaults, except that I tried to set password instead of relying on private key due to error- didn't help), but I can share that if needed.

Thanks alot. 
Rohail

**Comment by roumail** [comment]
I went back to the default vagrant file and tried to regenerate the (insecure) private key and ssh directly to the machine. 

Then I got the ssh_exchange_identification error:  read: Connection reset by peer. Could this be related to this virtualization option? I keep reading that this needs to be enabled

**Comment by jeroenjanssens** [comment]
Sorry to hear this. I don't know how to fix this.

Nowadays there's also a Docker image: https://hub.docker.com/r/datascienceworkshops/data-science-at-the-command-line/ . Hopefully this is an option for you.
