### ISSUE TITLE
Scrubbing Data (Page 56)

### ISSUE THREAD

**Issue by nuyori** [jeroenjanssens/data-science-at-the-command-line#57]
@jeroenjanssens
On page 56 the following bash snippet does not work "out of the box" in the vagrant / virtualbox environment running Ubuntu 14.04 LTS as suggested in the book:

```
$ echo 'foo\nbar\nfoo' | sort | uniq -c | sort -nr
1 foo\nbar\nfoo
$ echo 'foo\nbar\nfoo' | sort | uniq -c | sort -nr | awk '{print $2","$1}' | header -a value,count 
value,count
foo\nbar\nfoo,1
```

The following snippet works correctly with **-e** parameter given to echo:
```
$ echo -e 'foo\nbar\nfoo' | sort | uniq -c | sort -nr
2 foo
1 bar
$ echo -e 'foo\nbar\nfoo' | sort | uniq -c | sort -nr | awk '{print $2","$1}' | header -a value,count 
value,count
foo,2
bar,1
```

Alternative way would be using `printf` instead of `echo`. There might be also differences between distributions and versions of Unix in terms of using **-e** parameter with echo.

The following snippet might be more universally acceptable:

```
$ echo $'foo\nbar\nfoo' | sort | uniq -c | sort -nr
2 foo
1 bar
$ echo $'foo\nbar\nfoo' | sort | uniq -c | sort -nr | awk '{print $2","$1}' | header -a value,count 
value,count
foo,2
bar,1
```

**Comment by bisen2** [comment]
According to the [GNU documentation for echo](https://www.gnu.org/software/coreutils/echo) the -e flag should be compatible with all distros. It might be safer to implement the -e flag as it should work on any distribution regardless of if it is necessary

**Comment by jeroenjanssens** [comment]
Thanks for this. I'll make sure to fix this in the second edition.
