### ISSUE TITLE
Stuck after running Docker image

### ISSUE THREAD

**Issue by luipillmann** [jeroenjanssens/data-science-at-the-command-line#58]
Hi, Jeroen!

First of all, thanks for the awesome work and clear explanations about Data Science and Command Line Tools.

I've found the site when reading HN today. Then, I followed the through the first chapters until I got stuck at [2.2 Installing the Docker Image](https://www.datascienceatthecommandline.com/chapter-2-getting-started.html#docker-image). 

I'm aware it is currently a WIP to update the online version of the book. But I was wondering if there is something I could do to keep going once I ran the Docker container. Now, it seems the files you use are not there yet (e.g. `book/` folder), which makes it difficult to follow your first examples.

Am I missing something here? I would appreciate some help 😃 

Thanks in advance!

**Comment by jimoreira** [comment]
Same problem, im in a windows 10 home.
i get to the "cowsay" by using : 
$ docker-machine create box
$ docker-machine env box
$ @FOR /f “tokens=*” %i IN (‘docker-machine env box’) DO @%i
thanks to https://forums.docker.com/u/rishits85
but dont have the book directory .
Any help?? the book its awsome! 
thanks

**Comment by slacker298** [comment]
I also have the same problem.  Had no problem pulling the data, but when I enter the line:

`$ docker run --rm -itv"pwd":/data datascienceworkshops/data-science-at-the-command-line`

I am able to get the environment running, no problems with the cowsay command, but when I start looking around the files this is what I see when poking around the command line:

`[/data]$ pwd`
`/data`
`[/data]$ ls`
`[/data]$ cd /home`
`[/home]$ pwd`
`/home`
`[/home]$ ls`
`[/home]$ cd /book`
`bash: cd: /book: No such file or directory`
`[/data]$ cd`
`[~]$ pwd
'/root`
`[~]$ ls`

I feel it is important to point out that the ls command prints nothing - I guess that means that all of the directories are empty?  I can't say for sure, I am extremely inexperienced with respect to using the command line.  I have tried googling around for a solution but what I find seem only partially applicable to the problem and/or over my head.

I am excited to start learning and the book seems extremely relevant to my interests, so if anyone could shed some light on this issue I would be extremely grateful!  Thanks!

**Comment by Crevax** [comment]
Hey guys, I've taken a look at the [Dockerfile](https://hub.docker.com/r/datascienceworkshops/data-science-at-the-command-line/~/dockerfile/) and it looks like the `book` directory hasn't been copied in yet. So that's why you're not seeing anything yet. Hopefully Jeroen will have an update for that soon.

In the meantime, I've taken a moment to create a [gitter room](https://gitter.im/data-science-at-the-command-line/Lobby) for people to discuss the book. I've also forked the project to see if I can help contribute updates to the resources. I'm excited to go through the book, so I'd like to help out where I can.

**Comment by jeroenjanssens** [comment]
Once again thanks for fixing this @Crevax !
