### ISSUE TITLE
How to install tools manually from source

### ISSUE THREAD

**Issue by fengfengyuyu** [jeroenjanssens/data-science-at-the-command-line#65]
hi,
I am reading your book at [data-science-at-the-command-line](https://www.datascienceatthecommandline.com/chapter-2-getting-started.html).

I wanna install some of tools , such as 'Rio' , the book mentioned 'The installation instructions are for Ubuntu only'.

Would you be kindly to tell me where to get  'The installation instructions '.

Thanks in advance!

FengYu

**Comment by kubistmi** [comment]
Hello FengYu,
If I understand correctly, you would like to "install" some of the tools directly into your machine (without using Docker). While I am no expert, I have just imported some of the tools using following steps (should work on Linux distros, I have RHEL7):

1. Download the source codes and put them to some directory (I have used /home/*my_user*/tools, but I think /home/*my_user*/bin is typicall)
2. Edit your .bashrc (or .zshrc, or whatever shell you are using) by adding following line:
**export PATH=$PATH://home/*my_user*/tools** (IF NOT ALREADY SPECIFIED)
3. Load the new configuration by: **source .bashrc**

That should do the trick. 

Please, carefully review the **dependency** part of each tool to make sure you have utilities that the functions need to work properly.

Best,
Michal

**Comment by grocky** [comment]
I wrote a script that would download the tools in this repository. It's a little rough, but you can probably use it for your purposes.

https://github.com/grocky/data/blob/master/scripts/download-helper-scripts.js

**Comment by jeroenjanssens** [comment]
For the second edition, I'm planning on creating an Ansible playbook that will allow you to install all the tools on your host OS, whether that's Ubuntu or macOS. See #102 for more information.
