### ISSUE TITLE
Online book is missing appendix

### ISSUE THREAD

**Issue by ErikSwan** [jeroenjanssens/data-science-at-the-command-line#66]
The online version of the book is missing the [appendix](https://www.safaribooksonline.com/library/view/data-science-at/9781491947845/app01.html), which helpfully lists all of the command-line tools mentioned in the book with a brief description of each. It is mentioned several times in the text but seems to be missing from this repository and the hosted version of the book.

This is a super useful reference that I refer to often when trying to figure out how to do something on the command line, or to remind myself of tools that I don't use often—it should be included in the online version!

**Comment by jeroenjanssens** [comment]
Thanks, I agree that have a list of all the tools is useful. I'll make sure to have this back with the second edition.
