### ISSUE TITLE
Question for vagrant up 

### ISSUE THREAD

**Issue by JimmyHsuI** [jeroenjanssens/data-science-at-the-command-line#68]
I use virtual linux on my windows 7.
After I installed virtualbox and vagrant and followed the environment set up steps, the terminal show up the warming like this :
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/datatest1/.vagrant.d/boxes/data-science-toolbox-VAGRANTSLASH-data-science-at-the-command-line/1.0.0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "packer-virtualbox-iso_1523945099207_28351", "--vsys", "0", "--unit", "7", "--disk", "/home/datatest1/VirtualBox VMs/packer-virtualbox-iso_1523945099207_28351/packer-virtualbox-iso-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/datatest1/.vagrant.d/boxes/data-science-toolbox-VAGRANTSLASH-data-science-at-the-command-line/1.0.0/virtualbox/box.ovf...
OK.
0%...10%...20%...30%...40%...50%...60%...70%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/datatest1/VirtualBox VMs/packer-virtualbox-iso_1523945099207_28351/packer-virtualbox-iso-disk1.vmdk'.
VBoxManage: error: VMDK: cannot write allocated data block in '/home/datatest1/VirtualBox VMs/packer-virtualbox-iso_1523945099207_28351/packer-virtualbox-iso-disk1.vmdk' (VERR_DISK_FULL)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 886 of file VBoxManageAppliance.cpp

How can I fix it !!!!

**Comment by jeroenjanssens** [comment]
Hi @JimmyHsuI,

I'm sorry but I'm not sure what's going on here. May I suggest that you use Docker instead? Please see https://www.datascienceatthecommandline.com/chapter-2-getting-started.html#docker-image for instructions. If you have any questions about this then please open a new issue.
