### ISSUE TITLE
Wrong output to cols example in Ch. 3.2.1

### ISSUE THREAD

**Issue by SylvainLapoix** [jeroenjanssens/data-science-at-the-command-line#76]
I'm on Ubuntu 16.04.6 LTS

Trying to run the [ch 3.2.1](https://www.datascienceatthecommandline.com/chapter-5-scrubbing-data.html#working-with-csv) example on cols, I got a strange output : 

```
|        day |  bill |  tip | sex    | smoker | time   | size |
| ---------- | ----- | ---- | ------ | ------ | ------ | ---- |
| 0001-01-07 | 16,99 | 1,01 | Female |  False | Dinner |    2 |
| 0001-01-07 | 10,34 | 1,66 | Male   |  False | Dinner |    3 |
| 0001-01-07 | 21,01 | 3,50 | Male   |  False | Dinner |    3 |
| 0001-01-07 | 23,68 | 3,31 | Male   |  False | Dinner |    2 |
```
When switching 'day' w/ 'sex', the upper-case operation works but the day column is still messep up : 

```
| sex    |  bill |  tip | smoker |        day | time   | size |
| ------ | ----- | ---- | ------ | ---------- | ------ | ---- |
| FEMALE | 16,99 | 1,01 |  False | 0001-01-07 | Dinner |    2 |
| MALE   | 10,34 | 1,66 |  False | 0001-01-07 | Dinner |    3 |
| MALE   | 21,01 | 3,50 |  False | 0001-01-07 | Dinner |    3 |
| MALE   | 23,68 | 3,31 |  False | 0001-01-07 | Dinner |    2 |
```
I printed the head of my tips.csv (downloaded latest version) and it's all in order.

Any idea what went wrong ?

**Comment by jeroenjanssens** [comment]
Interest. Thanks for catching this. I suspect that this has to do with `csvkit`, which will be replaced by `xsv` in the second edition, so I will be closing this issue for now.
