### ISSUE TITLE
drake and grep: write error

### ISSUE THREAD

**Issue by jhagege** [jeroenjanssens/data-science-at-the-command-line#77]
Hi, great book ! 
I have an issue with running the first drake example:
![image](https://user-images.githubusercontent.com/7504908/48761254-e084d100-ecb0-11e8-8cb2-cba01bfb0c70.png)

Any clue ?

**Comment by jeroenjanssens** [comment]
Thanks for catching this. I have no idea what's causing this. Unfortunately, since Drake is no longer maintained, it will be replaced by Make in the second edition, so I'll be closing this issue.
