### ISSUE TITLE
Installing the docker image on Windows with WSL

### ISSUE THREAD

**Issue by Nathan-Furnal** [jeroenjanssens/data-science-at-the-command-line#94]
Hi all,

I believe I managed to have the environment up and running in Windows for thus of us who are interested. This requires the following steps, those are not too hard but can be time consuming. I'll assume you're using Windows 10.

1) Follow the steps described by Windows [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install).

This involves to 1.a) ensure you are a Windows Insider user, explained [here](https://insider.windows.com/en-us/)

and that you have 1.b) WSL up and running, explained [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

I had the following [issue](https://github.com/microsoft/WSL/issues/4103) but the fix is in the thread.

Next, and point 2) you'll need a valid docker setup with WSL 2, which is explained 

in 2.a) the docker [documentation](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

The following 2.b) article [was also helpful](https://www.thomasmaurer.ch/2019/08/run-linux-containers-with-docker-desktop-and-wsl-2/), be sure to run Windows containers.

Finally, with docker up and running as seen in the pictures and with a WSL prompt open you can simply use the steps describe in point 2 of the book.

The only thing I didn't get right is mapping the book to a directory with a docker ``volume``, if anyone has any ideas I'm all ears.

Hope it helps!

**Comment by jeroenjanssens** [comment]
Thanks for this. I must admit that I have very little experience with WSL and Docker. For the second edition of the book, I'm planning on making an Ansible playbook that will allow you to install all the tools on your host OS, hopefully also on WSL.

**Comment by Nathan-Furnal** [comment]
The new version of WSL, WSL2 ; is much easier to use now and it should be relatively handy as long as users are ok with working without GUI. I'm just a hobby user but I can check if it works out in the new version of your book once it's out!
